Document missing game parameters
Whist-Team/Whist-Server pull request #234
Opened 2022-06-12 21:24 UTC by abant07

I am not sure if I did the documentation correctly for all methods, so if you find any mistakes, please point them out.

Thanks

2022-06-12 21:35 UTC, Segelzwerg requested changes
@abant07 thanks for your PR. I think there is something wrong with indentation. We use 4 spaces in our projects and seems you used 2.

Also thanks for writing documentation for the private methods which we still can keep (haven't checked them though), but the task was to write the documentation of the parameters of the route method.

2022-06-12 21:43 UTC, iTitus commented
Just a quick question @abant07, are you using the web ui to edit the files?
Have you ever run the application or the tests locally?

2022-06-12 22:00 UTC, abant07 commented
Hi @iTitus 

Right now, I have been editing the on the GitHub website because it is easier, but I have GitHub downloaded on my desktop, so I could run locally.

2022-06-12 22:01 UTC, abant07 commented
Hi @Segelzwerg 

I have just finished with the documentation for this issue. Are there any other changes I should make?

Thanks

2022-06-12 22:11 UTC, Segelzwerg commented
> Hi @Segelzwerg 
> 
> I have just finished with the documentation for this issue. Are there any other changes I should make?
> 
> Thanks

@abant07 as I mentioned above the documentation is required in the route method. The privates are optional. We can keep them, previously we didn't bother writing them.

2022-06-12 22:18 UTC, Segelzwerg requested changes

2022-06-12 22:18 UTC, Segelzwerg commented on whist/server/api/game/create.py
> +    Sets the maximum and minimum level for players to join game.
It sets all game parameters.

2022-06-12 22:18 UTC, Segelzwerg commented on whist/server/api/game/create.py
> +    :return: the players in the game
No, please have a look again

2022-06-12 22:18 UTC, Segelzwerg commented on whist/server/api/game/create.py
> +    """
Try to understand what this method actually does. We don't even have player level, but ratings.

2022-06-12 22:18 UTC, Segelzwerg commented on whist/server/api/game/create.py
> +    Creates a game name.
Wording: the name is not created here

2022-06-12 22:18 UTC, Segelzwerg commented on whist/server/api/game/create.py
> +    :param request: Must contain a 'game_name'. 'password' is optional
Password not relevant

2022-06-12 22:18 UTC, Segelzwerg commented on whist/server/api/game/create.py
> +    """
See above

2022-06-12 22:29 UTC, iTitus commented
Hi @abant07 
> I have GitHub downloaded on my desktop, so I could run locally.

Please do that, if you use VSCode or an IDE like PyCharm to edit the files everything will be much easier for you, and for us as well!

2022-06-15 05:50 UTC, Segelzwerg commented
@abant07 thanks for writing the documentation for the private method, but the requirement is to expand the parameter doc in L19.

2022-06-15 05:53 UTC, Segelzwerg requested changes
@abant07 thanks for writing the documentation for the private method, but the requirement is to expand the parameter doc in L19.

2022-07-23 03:21 UTC, closed without merging