FEATURE: events and wrapper
Whist-Team/Whist-Server pull request #239
Opened 2022-06-14 21:26 UTC by Segelzwerg

2022-06-14 22:18 UTC, iTitus commented on whist/server/web_socket/subscriber.py
> +        wrapped_event = {event.name: event}
this should probably be another format. I'd suggest:
```suggestion
        wrapped_event = {'name': event.name, 'event': event}
```

2022-06-15 11:46 UTC, iTitus requested changes
Please fix the tests as well ;)

2022-06-15 12:18 UTC, Segelzwerg commented
> Please fix the tests as well ;)

Yes sure, committed your suggestion as reminder 😉

2022-06-16 12:58 UTC, iTitus approved these changes

2022-06-16 13:07 UTC, merged