ADD: favicon
Whist-Team/Whist-Server pull request #269
Opened 2022-06-25 23:35 UTC by Segelzwerg

source: https://icon-library.com/icon/ace-of-spades-icon-17.html

2022-06-25 23:41 UTC, iTitus requested changes
Why can't you just put the file into a static dir with the name favicon.ico?
-> https://fastapi.tiangolo.com/tutorial/static-files/

2022-06-25 23:44 UTC, Segelzwerg commented
> Why can't you just put the file into a static dir with the name favicon.ico? -> https://fastapi.tiangolo.com/tutorial/static-files/

yes, can try tomorrow

2022-06-26 09:51 UTC, Segelzwerg commented
> > Why can't you just put the file into a static dir with the name favicon.ico? -> https://fastapi.tiangolo.com/tutorial/static-files/
> 
> yes, can try tomorrow

Mounting is not feasible here because we have `app` declared in a central module and the routes are imported there. So best keep it that way.

2022-06-26 13:50 UTC, iTitus approved these changes

2022-06-26 13:50 UTC, merged