FIX: min max player in room
Whist-Team/Whist-Server pull request #377
Opened 2022-10-25 20:32 UTC by Segelzwerg

Requires https://github.com/Whist-Team/Whist-Core/pull/256 to be released
Fixes #375

2022-11-08 16:18 UTC, Segelzwerg commented
I have to revisit this one. May take a while.

2022-11-24 16:11 UTC, iTitus requested changes

2022-11-24 16:11 UTC, iTitus commented on pyproject.toml
> +whist-core = "^0.7.0"
```suggestion
whist-core = "^0.7"
fastapi = { version = ">=0.85,<0.87", extras = ["all"] }
httpx = "^0.23"
pydantic = "^1.10"
pymongo = "^4.3"
python-jose = { version = "^3.3", extras = ["cryptography"] }
splunk-sdk = "^1.7"
bcrypt = "^4.0"
```

2022-11-27 12:16 UTC, iTitus approved these changes

2022-11-27 12:16 UTC, merged