fix/pylint
Whist-Team/Whist-Server pull request #8
Opened 2021-04-19 23:25 UTC by Segelzwerg

2021-04-19 23:43 UTC, Segelzwerg commented
> partial deals with #7

actually upgraded scope of PR

2021-04-20 09:19 UTC, iTitus requested changes
Can you change the setup-python action to v2 ?

2021-04-20 09:19 UTC, iTitus commented on .github/workflows/codeql-analysis.yml
> +        # https://docs.github.com/en/free-pro-team@latest/githubmissing-module-docstring/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that
???
```suggestion
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed
```
???

2021-04-20 09:23 UTC, Segelzwerg commented on requirements.txt
> +uvicorn~=0.13.4
Ok I added it because it complaint locally.

2021-04-20 09:28 UTC, iTitus commented on requirements.txt
> +uvicorn~=0.13.4
Then you have to manually do `pip install fastapi[all]` in your venv

2021-04-20 09:29 UTC, Segelzwerg commented on requirements.txt
> +uvicorn~=0.13.4
Yeah I didn't realize it yesterday night. I removed uvicorn

2021-04-20 09:33 UTC, iTitus approved these changes

2021-04-20 09:34 UTC, merged